### ISSUE TITLE
Check visual ML api

### ISSUE THREAD

**Issue by mauricebrinkmann** [mauricebrinkmann/aibuildpack#3]
curl commands to
- train classification
- predict

**Comment by DanielWunder** [comment]
using Microsoft Costum Vision API you need more than just one http request to train a classification:
1st request: Create a project (if not using an existing project)
2nd request: Create a tag/classification
3rd request: Send images with tag
4th request: Train project

**Comment by DanielWunder** [comment]
https://southcentralus.dev.cognitive.microsoft.com/docs/services/Custom_Vision_Training_3.0/operations/5c771cdcbf6a2b18a0c3b80f

**Comment by DanielWunder** [comment]
curl -X POST \
  'https://{region}.api.cognitive.microsoft.com/customvision/v3.0/training/projects/{project-id}/images?tagIds={tagIds}' \
  -H 'Content-Type: multipart/form-data' \
  -H 'Trainig-Key: {subcription-key}' \
  -H 'Training-key: {subcription-key}' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F '=@{path1}' \
  -F '=@{path2}'

... add up to 64 files

**Comment by DanielWunder** [comment]
1st request: https://southcentralus.dev.cognitive.microsoft.com/docs/services/Custom_Vision_Training_3.0/operations/5c771cdcbf6a2b18a0c3b80f
2nd request: https://southcentralus.dev.cognitive.microsoft.com/docs/services/Custom_Vision_Training_3.0/operations/5c771cdcbf6a2b18a0c3b81f
3rd request: https://southcentralus.dev.cognitive.microsoft.com/docs/services/Custom_Vision_Training_3.0/operations/5c771cdcbf6a2b18a0c3b7ff (see example above)
4th request: https://southcentralus.dev.cognitive.microsoft.com/docs/services/Custom_Vision_Training_3.0/operations/5c771cdcbf6a2b18a0c3b813

**Comment by mauricebrinkmann** [comment]
It has been decided not to include this issue in the 0.2 release for the hackathon demo in favor to a stable demo and well-prepared presentation, which includes these ideas as a thoughtful outlook with detailed documentation of possible next steps.
